import json
import os
import smtplib
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from dotenv import load_dotenv

load_dotenv()


def send_email_alert(df, summary):
    """Formats the Day 1 tables and Day 2 AI summary into an HTML email and sends it via SMTP."""

    latest_data = df.iloc[-1]
    report_date = latest_data["Date"].strftime("%Y-%m-%d")

    # 1. Filter out only the metrics that triggered anomalies
    metrics = [
        col
        for col in df.columns
        if not any(
            suffix in col
            for suffix in [
                "_Baseline",
                "_Pct_Change",
                "_Z_Score",
                "_Anomaly",
                "Date",
            ]
        )
    ]

    flagged_metrics = []
    for metric in metrics:
        if latest_data[f"{metric}_Anomaly"]:
            flagged_metrics.append({
                "Metric": metric,
                "Value": latest_data[metric],
                "Baseline": latest_data[f"{metric}_Baseline_Avg"],
                "Shift": latest_data[f"{metric}_Pct_Change"],
            })

    # Circuit Breaker: If no anomalies exist, exit without sending an email
    if not flagged_metrics:
        print("[*] No anomalies detected. Email alert skipped.")
        return False

    # 2. Retrieve credentials
    sender_email = os.getenv("SENDER_EMAIL")
    sender_password = os.getenv("SENDER_PASSWORD")
    recipient_email = os.getenv("RECIPIENT_EMAIL")
    smtp_server = os.getenv("SMTP_SERVER", "smtp.gmail.com")
    smtp_port = int(os.getenv("SMTP_PORT", 587))

    if not sender_email or not sender_password or not recipient_email:
        raise ValueError(
            "Missing email credentials in .env file (SENDER_EMAIL, SENDER_PASSWORD, RECIPIENT_EMAIL)."
        )

    # 3. Construct HTML Table Rows for flagged metrics
    table_rows = ""
    for item in flagged_metrics:
        shift_color = "#d9534f" if item["Shift"] < 0 else "#28a745"
        table_rows += f"""
        <tr>
            <td style="padding: 10px; border-bottom: 1px solid #ddd;"><strong>{item['Metric']}</strong></td>
            <td style="padding: 10px; border-bottom: 1px solid #ddd;">{item['Value']:.2f}</td>
            <td style="padding: 10px; border-bottom: 1px solid #ddd;">{item['Baseline']:.2f}</td>
            <td style="padding: 10px; border-bottom: 1px solid #ddd; color: {shift_color};"><strong>{item['Shift']:+.1f}%</strong></td>
        </tr>
        """

    # 4. Build Complete HTML Email Body
    html_body = f"""
    <html>
    <body style="font-family: Arial, sans-serif; color: #333; line-height: 1.6;">
        <h2 style="color: #d9534f;">⚠️ Business Metric Alert — {report_date}</h2>
        
        <div style="background-color: #f8f9fa; border-left: 4px solid #007bff; padding: 15px; margin-bottom: 20px;">
            <h3 style="margin-top: 0; color: #007bff;">AI Executive Summary</h3>
            <p style="margin-bottom: 0;">{summary}</p>
        </div>

        <h3>Flagged Anomaly Metrics</h3>
        <table style="width: 100%; border-collapse: collapse; text-align: left;">
            <thead>
                <tr style="background-color: #f2f2f2;">
                    <th style="padding: 10px; border-bottom: 2px solid #ddd;">Metric</th>
                    <th style="padding: 10px; border-bottom: 2px solid #ddd;">Actual</th>
                    <th style="padding: 10px; border-bottom: 2px solid #ddd;">7-Day Avg</th>
                    <th style="padding: 10px; border-bottom: 2px solid #ddd;">Shift</th>
                </tr>
            </thead>
            <tbody>
                {table_rows}
            </tbody>
        </table>
        
        <p style="font-size: 12px; color: #777; margin-top: 30px;">
            Automated alert generated by Metric Watcher Agent on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}.
        </p>
    </body>
    </html>
    """

    # 5. Assemble MIME Email Message
    msg = MIMEMultipart("alternative")
    msg["Subject"] = (
        f"[ALERT] Anomaly Detected in Business Metrics ({report_date})"
    )
    msg["From"] = sender_email
    msg["To"] = recipient_email
    msg.attach(MIMEText(html_body, "html"))

    # 6. Dispatch Email via SMTP
    print("[*] Connecting to SMTP server and sending email alert...")
    try:
        with smtplib.SMTP(smtp_server, smtp_port) as server:
            server.starttls()
            server.login(sender_email, sender_password)
            server.sendmail(sender_email, recipient_email, msg.as_string())
        print("[✅] Email alert sent successfully!")

        # 7. Write Local Audit Log
        log_entry = {
            "timestamp": datetime.now().isoformat(),
            "report_date": report_date,
            "anomalies_count": len(flagged_metrics),
            "recipient": recipient_email,
            "status": "SENT",
        }

        log_file = "alert_history.json"
        history = []
        if os.path.exists(log_file):
            with open(log_file, "r") as f:
                try:
                    history = json.load(f)
                except json.JSONDecodeError:
                    history = []

        history.append(log_entry)
        with open(log_file, "w") as f:
            json.dump(history, f, indent=4)

        return True

    except Exception as e:
        print(f"[❌] Failed to send email: {str(e)}")
        return False